name: CI

on:
  push:
    branches: [ main, chore/** ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x, 20.x]
    env:
      NO_POSTINSTALL: 1
      SKIP_POSTINSTALL: 1
      CI: true
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
      - name: Show versions
        run: |
          node -v
          npm -v
      - name: Install dev deps (ignore scripts)
        run: npm install --ignore-scripts
      - name: Lint
        run: npm run lint --if-present
      - name: Tests
        run: npm test
      - name: Pack dry run
        run: npm pack --dry-run
      - name: Audit (prod)
        run: npm audit --omit=dev || true

